<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZF2Twig\Loader\Filesystem'                   => __DIR__ . '/src/ZF2Twig/Loader/Filesystem.php',
    'ZF2Twig\Loader\FilesystemFactory'            => __DIR__ . '/src/ZF2Twig/Loader/FilesystemFactory.php',
    'ZF2Twig\Environment\PluginProvider'          => __DIR__ . '/src/ZF2Twig/Environment/PluginProvider.php',
    'ZF2Twig\Environment\EnvironmentFactory'      => __DIR__ . '/src/ZF2Twig/Environment/EnvironmentFactory.php',
    'ZF2Twig\Environment\PluginProviderFactory'   => __DIR__ . '/src/ZF2Twig/Environment/PluginProviderFactory.php',
    'ZF2Twig\Environment\PluginProviderInterface' => __DIR__ . '/src/ZF2Twig/Environment/PluginProviderInterface.php',
    'ZF2Twig\Environment\Environment'             => __DIR__ . '/src/ZF2Twig/Environment/Environment.php',
    'ZF2Twig\Node\ZendViewHelper'                 => __DIR__ . '/src/ZF2Twig/Node/ZendViewHelper.php',
    'ZF2Twig\View\Strategy\TwigStrategy'          => __DIR__ . '/src/ZF2Twig/View/Strategy/TwigStrategy.php',
    'ZF2Twig\View\Strategy\TwigStrategyFactory'   => __DIR__ . '/src/ZF2Twig/View/Strategy/TwigStrategyFactory.php',
    'ZF2Twig\View\Renderer\TwigRenderer'          => __DIR__ . '/src/ZF2Twig/View/Renderer/TwigRenderer.php',
    'ZF2Twig\View\Renderer\TwigRendererFactory'   => __DIR__ . '/src/ZF2Twig/View/Renderer/TwigRendererFactory.php',
    'ZF2Twig\TokenParser\ZendViewHelper'          => __DIR__ . '/src/ZF2Twig/TokenParser/ZendViewHelper.php',
    'ZF2Twig\Module'                              => __DIR__ . '/Module.php',
);
